version: "3.0"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres

  admin:
    image: adminer
    ports:
      - 8085:8080